winners-locations:
  world: Spawn
  firstplace:
    x: 17.5
    y: 69
    z: -5.5
    yaw: 37
    pitch: 0
  secondplace:
    x: 19.5
    y: 68
    z: -1.5
    yaw: 49
    pitch: 0
  thirdplace:
    x: 13.5
    y: 67
    z: -7.5
    yaw: 27
    pitch: 0