name: EventHelper
version: '1.2.4'
main: com.michalovec.eventhelper.EventHelper
api-version: '1.21'
authors: [ Michalovec, LordKingCZ ]
depend: [ FancyNpcs, MultiWorld ]
softdepend: [ "PlaceholderAPI" ]

commands:
  gma:
    permission: eventhelper.gma
  gmc:
    permission: eventhelper.gmc
  gmsp:
    permission: eventhelper.gmsp
  gms:
    permission: eventhelper.gms
  tpall:
    permission: eventhelper.tpall
  tphere:
    aliases: [ s ]
    permission: eventhelper.tphere
  eventhelper:
    aliases: [ eh ]
    permission: eventhelper.eventhelper
  updateranks:
    permission: eventhelper.updateranks
  createwarp:
    permission: eventhelper.createwarp
  removewarp:
    permission: eventhelper.removewarp
  warp:
    permission: eventhelper.warp
  list:
    permission: eventhelper.list
  eventsettings:
    aliases: [ es ]
    permission: eventhelper.eventsettings
  heal:
    permission: eventhelper.heal
  feed:
    permission: eventhelper.feed
  speed:
    permission: eventhelper.speed
  win:
  tpalltospawn:
    permission: eventhelper.tpalltospawn

permissions:
  eventhelper.*:
    description: Všechna oprávnění pro EventHelper
    children:
      eventhelper.gma: true
      eventhelper.gmc: true
      eventhelper.gmsp: true
      eventhelper.gms: true
      eventhelper.tpall: true
      eventhelper.tphere: true
      eventhelper.eventhelper: true
      eventhelper.updateranks: true
      eventhelper.createwarp: true
      eventhelper.removewarp: true
      eventhelper.warp: true
      eventhelper.list: true
      eventhelper.eventsettings: true
      eventhelper.heal: true
      eventhelper.feed: true
      eventhelper.speed: true
      eventhelper.addwins: true
      eventhelper.tpalltospawn: true

  eventhelper.gma:
    default: op
    description: Povolení pro /gma
  eventhelper.gmc:
    default: op
    description: Povolení pro /gmc
  eventhelper.gmsp:
    default: op
    description: Povolení pro /gmsp
  eventhelper.gms:
    default: op
    description: Povolení pro /gms
  eventhelper.tpall:
    default: op
    description: Povolení pro /tpall
  eventhelper.tphere:
    default: op
    description: Povolení pro /tphere
  eventhelper.eventhelper:
    default: op
    description: Povolení pro /eventhelper nebo /eh
  eventhelper.updateranks:
    default: op
    description: Povolení pro /updateranks
  eventhelper.createwarp:
    default: op
    description: Povolení pro /createwarp
  eventhelper.removewarp:
    default: op
    description: Povolení pro /removewarp
  eventhelper.warp:
    default: op
    description: Povolení pro /warp
  eventhelper.list:
    default: op
    description: Povolení pro /list
  eventhelper.eventsettings:
    default: op
    description: Povolení pro /eventsettings nebo /es
  eventhelper.heal:
    default: op
    description: Povolení pro /heal
  eventhelper.feed:
    default: op
    description: Povolení pro /feed
  eventhelper.speed:
    default: op
    description: Povolení pro /speed
  eventhelper.addwins:
    default: op
    description: Povolení pro /win add
  eventhelper.tpalltospawn:
    default: op
    description: Povolení pro /tpalltospawn
  eventhelper.admin:
    description: Permise pro adminy
  eventhelper.hrac:
    default: not op
    description: Permise pro hráče

