name: EventHelper
version: '1.1'
main: com.michalovec.eventhelper.Main
api-version: '1.21'
authors: [ Michalovec, LordKingCZ ]
depend: [MultiWorld]

commands:
  chat:
    permission: eventhelper.chat
  gma:
    permission: eventhelper.gma
  gmc:
    permission: eventhelper.gmc
  gmsp:
    permission: eventhelper.gmsp
  gms:
    permission: eventhelper.gms
  tpall:
    permission: eventhelper.tpall
  tphere:
    aliases: [ s ]
    permission: eventhelper.tphere
  eventhelper:
    aliases: [ eh ]
    permission: eventhelper.eventhelper
  rank:
    permission: eventhelper.rank
  updateranks:
    permission: eventhelper.updateranks
  createwarp:
    permission: eventhelper.createwarp
  removewarp:
    permission: eventhelper.removewarp
  warp:
    permission: eventhelper.warp
  list:
    permission: eventhelper.list
  eventsettings:
    aliases: [ es ]
    permission: eventhelper.eventsettings
  worldgriefing:
    aliases: [ wg ]
    permission: eventhelper.worldgriefing
  worldgriefingbypass:
    aliases:
      - wgbypass
      - wgbp
    permission: eventhelper.worldgriefing
  heal:
    permission: eventhelper.heal
  feed:
    permission: eventhelper.feed
  speed:
    permission: eventhelper.speed

permissions:
  eventhelper.*:
    description: Všechna oprávnění pro EventHelper
    children:
      eventhelper.chat: true
      eventhelper.gma: true
      eventhelper.gmc: true
      eventhelper.gmsp: true
      eventhelper.gms: true
      eventhelper.tpall: true
      eventhelper.tphere: true
      eventhelper.eventhelper: true
      eventhelper.rank: true
      eventhelper.updateranks: true
      eventhelper.createwarp: true
      eventhelper.removewarp: true
      eventhelper.warp: true
      eventhelper.list: true
      eventhelper.eventsettings: true
      eventhelper.worldgriefing: true
      eventhelper.heal: true
      eventhelper.feed: true
      eventhelper.speed: true

  eventhelper.chat:
    description: Povolení pro /chat
  eventhelper.gma:
    description: Povolení pro /gma
  eventhelper.gmc:
    description: Povolení pro /gmc
  eventhelper.gmsp:
    description: Povolení pro /gmsp
  eventhelper.gms:
    description: Povolení pro /gms
  eventhelper.tpall:
    description: Povolení pro /tpall
  eventhelper.tphere:
    description: Povolení pro /tphere
  eventhelper.eventhelper:
    description: Povolení pro /eventhelper nebo /eh
  eventhelper.rank:
    description: Povolení pro /rank
  eventhelper.updateranks:
    description: Povolení pro /updateranks
  eventhelper.createwarp:
    description: Povolení pro /createwarp
  eventhelper.removewarp:
    description: Povolení pro /removewarp
  eventhelper.warp:
    description: Povolení pro /warp
  eventhelper.list:
    description: Povolení pro /list
  eventhelper.eventsettings:
    description: Povolení pro /eventsettings nebo /es
  eventhelper.worldgriefing:
    description: Povolení pro /worldgriefing nebo /wg
  eventhelper.heal:
    description: Povolení pro /heal
  eventhelper.feed:
    description: Povolení pro /feed
  eventhelper.speed:
    description: Povolení pro /speed

